### ISSUE TITLE
Wrong waitting loop mode in MT25TL01G_Enter4BytesAddressMode 

### ISSUE THREAD

**Issue by anton-bondarev** [STMicroelectronics/mt25tl01g#2]
Hello,
It seems that there is a bug with the mode access in MT25TL01G_Enter4BytesAddressMode()

```int32_t MT25TL01G_Enter4BytesAddressMode(QSPI_HandleTypeDef *Ctx, MT25TL01G_Interface_t Mode)
{
  QSPI_CommandTypeDef s_command;

  /* Initialize the command */
  s_command.InstructionMode   = (Mode == MT25TL01G_QPI_MODE) ? QSPI_INSTRUCTION_4_LINES : QSPI_INSTRUCTION_1_LINE;
  s_command.Instruction       = MT25TL01G_ENTER_4_BYTE_ADDR_MODE_CMD;
...

  /* Configure automatic polling mode to wait the memory is ready */
  else if(MT25TL01G_AutoPollingMemReady(Ctx,Mode)!=MT25TL01G_OK)
  {
    return MT25TL01G_ERROR_COMMAND;
  }
...
```
We set up MT25TL01G_ENTER_4_BYTE_ADDR_MODE_CMD mode, but wat in MT25TL01G_AutoPollingMemReady with old Mode which can be BSP_QSPI_SPI_MODE.

It is reproduced for me on my 'STM32h745i-discovery' board. BSP_QSPI_Init() returns -5; I create PR #1 it fixes the problem for me.

**Comment by RKOUSTM** [comment]
Hi @anton-bondarev,
 
Thank you for your report. Regarding the `QSPI` device configuration, we cannot set the Interface Mode for `MT25TL01G_AutoPollingMemReady()` function only `MT25TL01G_QPI_MODE`. In your application, just call `BSP_QSPI_Init()` with the interface mode `MT25TL01G_QPI_MODE`, as is illustrated in the following `QSPI demo` example:

```
void QSPI_demo (void)
{
  /* QSPI info structure */
  BSP_QSPI_Info_t pQSPI_Info;
  uint8_t status;

  QSPI_SetHint();

  /*##-1- Configure the QSPI device ##########################################*/
  /* QSPI device configuration */
  BSP_QSPI_Init_t init ;
  init.InterfaceMode=MT25TL01G_QPI_MODE;
  init.TransferRate= MT25TL01G_DTR_TRANSFER ;
  init.DualFlashMode= MT25TL01G_DUALFLASH_ENABLE;
  status = BSP_QSPI_Init(0,&init);
```
 You can refer to [this](https://github.com/STMicroelectronics/STM32CubeH7/tree/master/Projects/STM32H747I-EVAL/Examples/BSP) example of `BSP` on the `STM32H747I-EVAL` to know how to write, read and compare buffers for external flash memory using QSPI communication.

I hope this will help you overcome the issue you are facing. 

Please let me know if this is the case or if you still need help. Thank you again for your report.

With regards,

**Comment by anton-bondarev** [comment]
@RKOUSTM Thank you for the response. I'll check it ASAP.
